### PR TITLE
feat: update lessons files to cairo-v0.10.0

### PR DESCRIPTION
**Pull request by dan-ziv**
### Description of the Changes

Align lessons files to cairo-v0.10.0 syntax.

### Checklist

- [ ] Changes have been done against master branch, and PR does not conflict
- [ ] New unit / functional tests have been added (whenever applicable)
- [ ] Test are passing in local environment
- [ ] Docs have been updated
- [ ] PR title is follow the [standard-version](https://www.conventionalcommits.org/) convention: `<type>(optional subject): <description>`, e.g: `fix: minor typos in code`

- - -
This change is [Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-playground/23)

### CODE REVIEW

**Review by adi-yakovian-starkware — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-playground/23)* status: all files reviewed, 8 unresolved discussions (waiting on @dan-ziv, @ilyalesokhin-starkware, and @liorgold2)

___
*[`public/lessons/felt.cairo` line 12 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQmWQu28-POCQRzFzC:-NBQmWQu28-POCQRzFzD:bpucwjx) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/felt.cairo#L12)):*
> ```Cairo
> // Division of field elements (and therefore division in Cairo) is not the
> // integer division you may be used to.
> // In the next challenge, you'll see how to use unsigned_div_rem()
> ```

I'm guessing you changed it to `lesson` on purpose, so I think this change should be reverted (and updated in `cairo-v0.10.0`/`cairo-v0.10.1`).



_Code quote:_
```Cairo
challenge
```
___
*[`public/lessons/felt2.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQn_Ma0ihLdMf9xDxX:-NBQn_Ma0ihLdMf9xDxY:b2nreh6) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/felt2.cairo#L1)):*
> ```Cairo
> // As you saw in the previous challenge, the operator '/' does not denote
> ```

Same as above.



_Code quote:_
```Cairo
challenge
```
___
*[`public/lessons/hello_playground.cairo` line 7 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQotM3BAdy04bIuym-:-NBQotM3BAdy04bIuym0:b-x8hpzi) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/hello_playground.cairo#L7)):*
> ```Cairo
> // If you want to install it, you can read the instructions [here](https://www.cairo-lang.org/docs/quickstart.html).
> //
> // On the top-right corner, you should see the "Challenges" button.
> ```

Same as above, and same for the ones below :)



_Code quote:_
```Cairo
Challenge
```
___
*[`public/lessons/local_var_addr.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQpntq7kzh6aERkFoK:-NBQpntq7kzh6aERkFoL:b2nreh6) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/local_var_addr.cairo#L14)):*
> ```Cairo
> // 3. Uncomment the line calling foo() and try to run the code.
> //    Fix the code by adding exactly one word to it.
> //    Hint: Revisit the "Revoked references" challenge.
> ```

Same as above.



_Code quote:_
```Cairo
challenge
```
___
*[`public/lessons/starknet_contract.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQuxnZ76a_-SSyNqaq:-NBQuxnZ76a_-SSyNqar:bsnuyxr) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/7417f6886502628ab01277b77bd2db40a15ac895/public/lessons/starknet_contract.cairo#L14)):*
> ```Cairo
> #    ["Hello StarkNet" tutorial](https://cairo-lang.org/docs/hello_starknet).
> # 2. Click on the contract address in the output pane to open
> #    [Voyager](https://goerli.voyager.online/) - the StarkNet block explorer.
> ```

@dan-ziv, @liorgold2, which one is the right one?
I don't see this change (adding `goerli` to the url) in our repos, but I think this should have been done.



_Code quote:_
```Cairo
goerli.voyager.online
```
___
*[`public/lessons/starknet_contract.cairo` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQwSJq8xQUEQHEdh9m:-NBQwSJq8xQUEQHEdh9n:bvrg6l4) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/starknet_contract.cairo#L22)):*
> ```Cairo
> %lang starknet
> 
> // The "%builtins" directive declares the builtins used by the contract.
> ```

@liorgold2, this does not appear in the  `playground-react` file in our repos, is this directory no more relevant? If so, can we delete it?



_Code quote:_
```Cairo
// The "%builtins" directive declares the builtins used by the contract.
// For example, the "range_check" builtin is used to compare values.
%builtins range_check
```
___
*[`public/lessons/structs.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQwyEt5QDtcyNNxp7Q:-NBQwyEt5QDtcyNNxp7R:b-ran8hd) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/structs.cairo#L1)):*
> ```Cairo
> // In this challenge you're going to implement a stack using a linked list.
> ```

Same as before (challenge -> lesson).



_Code quote:_
```Cairo
challenge
```
___
*[`public/lessons/variables.cairo` line 26 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQyqeIEfVnvNdsaV4H:-NBQyqeIEfVnvNdsaV4I:b-ran8hd) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/variables.cairo#L26)):*
> ```Cairo
> // the keyword `local` allocates a new variables for the
> // intermediate values as well. The main difference between
> // `local` and `tempvar` is explained in the next challenge.
> ```

Same as before (challenge -> lesson).



_Code quote:_
```Cairo
challenge
```

**Review by adi-yakovian-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-playground/23)* status: all files reviewed, 22 unresolved discussions (waiting on @dan-ziv, @ilyalesokhin-starkware, and @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRFi6ECLuBSxdKJpBQ:-NBRFi6ECLuBSxdKJpBR:bahi9kp) (no related file):*
@dan-ziv, @liorgold2  I've also added some non-blocking comments for you to consider.

___
___
*[`public/lessons/hints.cairo` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBR7IGuBUhqoEJzNBr4:-NBR7IGvCOYhVy7RvE3e:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/hints.cairo#L6)):*
> ```Cairo
> // it doesn't really care how res was computed.
> // In such cases, we don't have to compute res in pure Cairo - we can write a
> // piece of python code inside the Cairo program, which is called a "hint".
> ```





_Suggestion:_
```Cairo
Python
```
___
*[`public/lessons/hints.cairo` line 28 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBR7kwG6EuxPBjOto41:-NBR7kwG6EuxPBjOto42:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/hints.cairo#L28)):*
> ```Cairo
>     local res;
> 
>     // Set the value of res using a python hint.
> ```





_Suggestion:_
```Cairo
Python
```
___
*[`public/lessons/local_var_addr.cairo` line 10 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBR8Gzm-rcn92dZlgdO:-NBR8Gzm-rcn92dZlgdP:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/local_var_addr.cairo#L10)):*
> ```Cairo
> // 1. Try to run the code as-is, and make sure you understand the error.
> // 2. Uncomment the line setting __fp__, and run again.
> //    The code should now work and you should be able to see that x was set
> ```





_Suggestion:_
```Cairo
`x`
```
___
*[`public/lessons/pedersen.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBR9HXI1LejqJQyal2G:-NBR9HXI1LejqJQyal2H:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/pedersen.cairo#L13)):*
> ```Cairo
> // Note: Don't use starkware.cairo.common.hash_chain (it computes the chain differently).
> 
> // Use the pedersen builtin.
> ```





_Suggestion:_
```Cairo
Pedersen
```
___
*[`public/lessons/recursion.cairo` line 19 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRAFzB4qGOrw0Zv5a6:-NBRAFzB4qGOrw0Zv5a7:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/recursion.cairo#L19)):*
> ```Cairo
>     }
> 
>     // Otherwise, call `compute_sum` recursively to compute 1 + 2 + ... + (n-1)
> ```





_Suggestion:_
```Cairo
compute 1 + 2 + ... + (n-1).
```
___
*[`public/lessons/revoked.cairo` line 5 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRAY0S1Yay-YWf2UMs:-NBRAY0S1Yay-YWf2UMt:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/revoked.cairo#L5)):*
> ```Cairo
> // For example, a call to another function may revoke those references.
> //
> // 1. Try to run the following code. You should get an error that x was revoked
> ```





_Suggestion:_
```Cairo
`x`
```
___
*[`public/lessons/revoked.cairo` line 6 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRAbA051ZdfNtrCSHn:-NBRAbA051ZdfNtrCSHo:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/revoked.cairo#L6)):*
> ```Cairo
> //
> // 1. Try to run the following code. You should get an error that x was revoked
> //    (this is because of the second call to foo).
> ```





_Suggestion:_
```Cairo
`foo`
```
___
*[`public/lessons/sharp.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRB9578UPER0I4CaSX:-NBRB9578UPER0I4CaSY:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/sharp.cairo#L1)):*
> ```Cairo
> // The program below lets you to choose a number x and output its square y = x*x
> ```





_Suggestion:_
```Cairo
choose
```
___
*[`public/lessons/sharp.cairo` line 1 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRBG2L-jXg9pYSYR_R:-NBRBG2L-jXg9pYSYR_S:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/sharp.cairo#L1)):*
> ```Cairo
> // The program below lets you to choose a number x and output its square y = x*x
> ```





_Suggestion:_
```Cairo
`x`
```
___
*[`public/lessons/sharp.cairo` line 2 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRBO-e9VRxkSd_yjGF:-NBRBO-e9VRxkSd_yjGG:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/sharp.cairo#L2)):*
> ```Cairo
> // The program below lets you to choose a number x and output its square y = x*x
> // (proving that you know the square root of y).
> ```





_Suggestion:_
```Cairo
`y`
```
___
*[`public/lessons/sharp.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRBZQZ2N_ZyEWkLwv6:-NBRBZQZ2N_ZyEWkLwv7:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/sharp.cairo#L13)):*
> ```Cairo
> //    so changing any code within a hint does not change the resulting program
> //    hash.
> //    Try changing x to a different number and note that the program hash remains
> ```





_Suggestion:_
```Cairo
`x`
```
___
*[`public/lessons/sharp.cairo` line 30 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRC1ULCiu4txZZcSKI:-NBRC1ULCiu4txZZcSKJ:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/sharp.cairo#L30)):*
> ```Cairo
> // 4. You can monitor the status of your job, using the link in the output pane.
> //
> // For each job the corresponding fact is computed as follows:
> ```





_Suggestion:_
```Cairo
For each job,
```
___
*[`public/lessons/sharp.cairo` line 50 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRCeja4eV0IMo4NMv0:-NBRCeja4eV0IMo4NMv1:undefined) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/sharp.cairo#L50)):*
> ```Cairo
> //   ])
> //
> // You can also find your job's fact in SHARP tracking page you opened
> ```





_Suggestion:_
```Cairo
the SHARP tracking page
```
___
*[`public/lessons/starknet_contract.cairo` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQwSJq8xQUEQHEdh9m:-NBRDIztD9JmfxuhrPqV:b-9cwpna) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/starknet_contract.cairo#L22)):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

@liorgold2, this does not appear in the  `playground-react` file in our repos, is this directory no more relevant? If so, can we delete it?
</blockquote></details>

(also, this builtin isn't being used, no? is it on purpose?)

**Review by adi-yakovian-starkware — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-playground/23)* status: all files reviewed, 23 unresolved discussions (waiting on @dan-ziv, @ilyalesokhin-starkware, and @liorgold2)

*[a discussion](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRFi6ECLuBSxdKJpBQ:-NBRNVjT6dMS-CJ013fx:b-tbxck8) (no related file):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

@dan-ziv, @liorgold2  I've also added some non-blocking comments for you to consider.
</blockquote></details>

@dan-ziv, if you prefer, I can add fixes to the non-blocking comments on `cairo-v0.10.0`, and then you'll be able to copy them here. 

___
___
*[`public/lessons/starknet_contract.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQuxnZ76a_-SSyNqaq:-NBROY8D-yo76R309-ER:bywl2rw) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/7417f6886502628ab01277b77bd2db40a15ac895/public/lessons/starknet_contract.cairo#L14)):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

@dan-ziv, @liorgold2, which one is the right one?
I don't see this change (adding `goerli` to the url) in our repos, but I think this should have been done.
</blockquote></details>

@dan-ziv, I talked with Lior and this change should indeed be reverted (I'll add this fix to `cairo-v0.10.0`. 
___
*[`public/lessons/starknet_contract.cairo` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBRMpBX9DmkgG15DlUh:-NBRMpBY5c3lWAQdiSc1:b-yz9wul) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/starknet_contract.cairo#L22)):*
> ```Cairo
> %lang starknet
> 
> // The "%builtins" directive declares the builtins used by the contract.
> ```

@dan-ziv, I talked with Lior, and this should be removed (there's no longer a need for the %builtins directive in StarkNet contracts).



_Code quote:_
```Cairo
// The "%builtins" directive declares the builtins used by the contract.
// For example, the "range_check" builtin is used to compare values.
%builtins range_check
```
___
*[`public/lessons/starknet_contract.cairo` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQwSJq8xQUEQHEdh9m:-NBRN7Hi5xzLJETPCU8b:b-1ddf9w) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/starknet_contract.cairo#L22)):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

(also, this builtin isn't being used, no? is it on purpose?)
</blockquote></details>

@dan-ziv, Lior agreed that the  `playground-react` directory should probably be removed from the `starkware` repos, WDYT?

**Comment by dan-ziv** [comment]
*[`public/lessons/starknet_contract.cairo` line 22 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQwSJq8xQUEQHEdh9m:-NBS5tTn1sAAP83Rn1Rg:b-9zzsay) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/starknet_contract.cairo#L22)):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

@dan-ziv, Lior agreed that the  `playground-react` directory should probably be removed from the `starkware` repos, WDYT?
</blockquote></details>

Yes, we can delete it from there.

**Comment by dan-ziv** [comment]
*[`public/lessons/starknet_contract.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQuxnZ76a_-SSyNqaq:-NBS60Gy4kf93fknQrKY:bh5u5pi) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/7417f6886502628ab01277b77bd2db40a15ac895/public/lessons/starknet_contract.cairo#L14)):*
<details><summary><i>Previously, Adi-Yakovian wrote…</i></summary><blockquote>

@dan-ziv, I talked with Lior and this change should indeed be reverted (I'll add this fix to `cairo-v0.10.0`. 
</blockquote></details>

ok, LMK when I can pull it again

**Comment by adi-yakovian-starkware** [comment]
*[`public/lessons/starknet_contract.cairo` line 14 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBQuxnZ76a_-SSyNqaq:-NBfCI8mDIjaAJGCRMGV:by0jevj) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/7417f6886502628ab01277b77bd2db40a15ac895/public/lessons/starknet_contract.cairo#L14)):*
<details><summary><i>Previously, dan-ziv (DanZ) wrote…</i></summary><blockquote>

ok, LMK when I can pull it again
</blockquote></details>

You can now :)

**Review by adi-yakovian-starkware — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starkware-libs/cairo-playground/23)* status: all files reviewed, 8 unresolved discussions (waiting on @dan-ziv and @liorgold2)

___
*[`public/lessons/pedersen.cairo` line 13 at r1](https://reviewable.io/reviews/starkware-libs/cairo-playground/23#-NBR9HXI1LejqJQyal2G:-NBfVRVY2_LwjOtE4gzk:b-qbb3si) ([raw file](https://github.com/starkware-libs/cairo-playground/blob/c5cb1c882c650df491529b3927e09d644f6bd46f/public/lessons/pedersen.cairo#L13)):*
> ```Cairo
> // Note: Don't use starkware.cairo.common.hash_chain (it computes the chain differently).
> 
> // Use the pedersen builtin.
> ```

Apparently, I made this change in the playground-react directory :woman_facepalming:. Could you only make this change when making the `challenge` -> `lesson` changes? (I'll make this change on 0.10.0)

**Review by adi-yakovian-starkware — APPROVED** [review]

**Pull request merged**
